name: CI/CD Pipeline with Docker

on:
  push:
    branches: [ master]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Run Docker container
      run: docker run -d -p 3000:3000 myapp
